[dist]
cargo-dist-version = "0.25.1"
installers = ["shell", "powershell", "homebrew", "msi"]
targets = [
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "x86_64-pc-windows-msvc",
]
ci  = ["github"]
tap = "Sakib-Dalal/homebrew-tap"
install-path = "CARGO_HOME"
