[package]
name        = "mammoth-rpc"
description = "Transport, connection pooling and auth"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[dependencies]
mammoth-core = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
