//! Small repository tasks. Paths are resolved from this crate, not the caller's cwd.

use std::path::Path;
use std::process::{Command, ExitCode};

use clap::CommandFactory;

// Share the actual command tree, so help and committed documentation stay in sync.
#[allow(dead_code)]
#[path = "../../crates/mammoth-cli/src/cli.rs"]
mod cli;

fn main() -> ExitCode {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().expect("workspace root");
    match run(root, std::env::args().nth(1).as_deref()) {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("xtask: {error}");
            ExitCode::FAILURE
        }
    }
}

fn run(root: &Path, task: Option<&str>) -> Result<(), Box<dyn std::error::Error>> {
    match task {
        Some("build-ui") => {
            let npm = if cfg!(windows) { "npm.cmd" } else { "npm" };
            command(&root.join("ui"), npm, &["ci"])?;
            command(&root.join("ui"), npm, &["run", "build"])?;
        }
        Some("docs") => {
            let mut text = String::from(
                "---\ntitle: CLI reference\ndescription: Generated from the Mammoth command tree.\n---\n\n\
                 <!-- Generated by cargo xtask docs. Edit crates/mammoth-cli/src/cli.rs instead. -->\n\n\
                 The local filesystem, dashboard, HTTP client, text jobs and S3 subset are implemented.\n\
                 Separate master/worker roles remain future work. See docs/IMPLEMENTATION-STATUS.md.\n\n",
            );
            render_help(cli::Cli::command(), "mammoth", &mut text);
            std::fs::write(
                root.join("web/src/content/docs/cli/reference.md"),
                format!("{}\n", text.trim_end()),
            )?;
        }
        Some("assets") => {
            let logo = root.join("assets/logo/mammoth-logo.svg");
            for destination in ["ui/static/logo.svg", "web/public/logo.svg"] {
                std::fs::copy(&logo, root.join(destination))?;
            }
        }
        Some("dist") => {
            run(root, Some("build-ui"))?;
            command(root, "cargo", &["build", "--release", "--locked", "-p", "mammoth-cli"])?;
            let output = Command::new("rustc").arg("-vV").output()?;
            if !output.status.success() {
                return Err("could not determine build target".into());
            }
            let version = String::from_utf8(output.stdout)?;
            let target = version
                .lines()
                .find_map(|line| line.strip_prefix("host: "))
                .ok_or("rustc did not report its host target")?;
            let distribution = root.join("target/dist");
            let package = distribution.join(format!("mammoth-{target}"));
            std::fs::create_dir_all(&package)?;
            let binary = if cfg!(windows) { "mammoth.exe" } else { "mammoth" };
            std::fs::copy(root.join("target/release").join(binary), package.join(binary))?;
            for name in ["README.md", "LICENSE-APACHE", "LICENSE-MIT"] {
                std::fs::copy(root.join(name), package.join(name))?;
            }
            std::fs::copy(
                root.join("docs/IMPLEMENTATION-STATUS.md"),
                package.join("IMPLEMENTATION-STATUS.md"),
            )?;
            let archive = distribution.join(format!("mammoth-{target}.tar.gz"));
            let status = Command::new("tar")
                .arg("-czf")
                .arg(&archive)
                .arg("-C")
                .arg(&package)
                .arg(".")
                .status()?;
            if !status.success() {
                return Err("archive creation failed".into());
            }
            println!("{}", archive.display());
        }
        _ => return Err("usage: cargo xtask <build-ui|docs|assets|dist>".into()),
    }
    Ok(())
}

fn command(dir: &Path, program: &str, args: &[&str]) -> Result<(), Box<dyn std::error::Error>> {
    let status = Command::new(program).args(args).current_dir(dir).status()?;
    if !status.success() {
        return Err(format!("{program} {} failed ({status})", args.join(" ")).into());
    }
    Ok(())
}

fn render_help(mut command: clap::Command, name: &str, output: &mut String) {
    command = command.bin_name(name).color(clap::ColorChoice::Never);
    // Build first so child commands inherit global flags just like the CLI.
    command.build();
    output.push_str(&format!(
        "## `{name}`\n\n```text\n{}\n```\n\n",
        command
            .render_long_help()
            .to_string()
            .lines()
            .map(str::trim_end)
            .collect::<Vec<_>>()
            .join("\n")
    ));
    for child in command.get_subcommands().filter(|child| child.get_name() != "help") {
        render_help(child.clone(), &format!("{name} {}", child.get_name()), output);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reference_includes_nested_commands_and_global_flags() {
        let mut text = String::new();
        render_help(cli::Cli::command(), "mammoth", &mut text);
        assert!(text.contains("## `mammoth viz blocks`"));
        let blocks = text.split("## `mammoth viz blocks`").nth(1).unwrap();
        assert!(blocks.split("## ").next().unwrap().contains("--json"));
        assert!(!text.contains('\u{1b}'));
    }
}
