//! Small repository tasks. Paths are resolved from this crate, not the caller's cwd.

use std::path::Path;
use std::process::{Command, ExitCode};

use clap::CommandFactory;

// Share the actual command tree, so help and committed documentation stay in sync.
#[allow(dead_code)]
#[path = "../../crates/mammoth-cli/src/cli.rs"]
mod cli;

fn main() -> ExitCode {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().expect("workspace root");
    match run(root, std::env::args().nth(1).as_deref()) {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("xtask: {error}");
            ExitCode::FAILURE
        }
    }
}

fn run(root: &Path, task: Option<&str>) -> Result<(), Box<dyn std::error::Error>> {
    match task {
        Some("build-ui") => {
            let npm = if cfg!(windows) { "npm.cmd" } else { "npm" };
            command(&root.join("ui"), npm, &["ci"])?;
            command(&root.join("ui"), npm, &["run", "build"])?;
        }
        Some("docs") => {
            let mut text = String::from(
                "---\ntitle: CLI reference\ndescription: Generated from the Mammoth command tree.\n---\n\n\
                 <!-- Generated by cargo xtask docs. Edit crates/mammoth-cli/src/cli.rs instead. -->\n\n\
                 This is the declared command surface. Memory and MCP are implemented. Legacy storage command implementations remain\n\
                 scaffolds; help output does not imply that a command works yet.\n\n",
            );
            render_help(cli::Cli::command(), "mammoth", &mut text);
            std::fs::write(
                root.join("web/src/content/docs/cli/reference.md"),
                format!("{}\n", text.trim_end()),
            )?;
        }
        Some("assets") => {
            let logo = root.join("assets/logo/mammoth-logo.svg");
            for destination in ["ui/static/logo.svg", "web/public/logo.svg"] {
                std::fs::copy(&logo, root.join(destination))?;
            }
        }
        Some("dist") => return Err("release packaging is not implemented on the manual main track; complete and validate the readiness gates in docs/guide/14-readiness-and-benchmarks.md first".into()),
        _ => return Err("usage: cargo xtask <build-ui|docs|assets|dist>".into()),
    }
    Ok(())
}

fn command(dir: &Path, program: &str, args: &[&str]) -> Result<(), Box<dyn std::error::Error>> {
    let status = Command::new(program).args(args).current_dir(dir).status()?;
    if !status.success() {
        return Err(format!("{program} {} failed ({status})", args.join(" ")).into());
    }
    Ok(())
}

fn render_help(mut command: clap::Command, name: &str, output: &mut String) {
    command = command.bin_name(name).color(clap::ColorChoice::Never);
    // Build first so child commands inherit global flags just like the CLI.
    command.build();
    output.push_str(&format!(
        "## `{name}`\n\n```text\n{}\n```\n\n",
        command
            .render_long_help()
            .to_string()
            .lines()
            .map(str::trim_end)
            .collect::<Vec<_>>()
            .join("\n")
    ));
    for child in command.get_subcommands().filter(|child| child.get_name() != "help") {
        render_help(child.clone(), &format!("{name} {}", child.get_name()), output);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reference_includes_nested_commands_and_global_flags() {
        let mut text = String::new();
        render_help(cli::Cli::command(), "mammoth", &mut text);
        assert!(text.contains("## `mammoth viz blocks`"));
        let blocks = text.split("## `mammoth viz blocks`").nth(1).unwrap();
        assert!(blocks.split("## ").next().unwrap().contains("--json"));
        assert!(!text.contains('\u{1b}'));
    }
}
