//! Small repository tasks. Paths are resolved from this crate, not the caller's cwd.

use sha2::{Digest, Sha256};
use std::io::Read;
use std::path::Path;
use std::process::{Command, ExitCode};

// Share the actual command tree, so help and committed documentation stay in sync.
#[allow(dead_code)]
#[path = "../../crates/mammoth-cli/src/cli.rs"]
mod cli;

fn main() -> ExitCode {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().expect("workspace root");
    match run(root, std::env::args().nth(1).as_deref()) {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("xtask: {error}");
            ExitCode::FAILURE
        }
    }
}

fn run(root: &Path, task: Option<&str>) -> Result<(), Box<dyn std::error::Error>> {
    match task {
        Some("build-ui") => {
            let npm = if cfg!(windows) { "npm.cmd" } else { "npm" };
            command(&root.join("ui"), npm, &["ci"])?;
            command(&root.join("ui"), npm, &["run", "build"])?;
        }
        Some("docs") => {
            let mut text = String::from(
                "---\ntitle: CLI reference\ndescription: Generated from the Mammoth command tree.\n---\n\n\
                 <!-- Generated by cargo xtask docs. Edit crates/mammoth-cli/src/cli.rs instead. -->\n\n\
                 The local filesystem, dashboard, HTTP client, text jobs and S3 subset are implemented.\n\
                 Separate master/worker roles remain future work. See docs/IMPLEMENTATION-STATUS.md.\n\n",
            );
            render_help(cli::Cli::help_command(), "mammoth", &mut text);
            std::fs::write(
                root.join("web/src/content/docs/cli/reference.md"),
                format!("{}\n", text.trim_end()),
            )?;
        }
        Some("assets") => {
            let logo = root.join("assets/logo/mammoth-logo.svg");
            for destination in ["ui/static/logo.svg", "web/public/logo.svg"] {
                std::fs::copy(&logo, root.join(destination))?;
            }
        }
        Some("dist") => {
            run(root, Some("build-ui"))?;
            command(root, "cargo", &["build", "--release", "--locked", "-p", "mammoth-cli"])?;
            package(root, None)?;
        }
        Some("package") => package(root, std::env::args().nth(2).as_deref())?,
        _ => return Err("usage: cargo xtask <build-ui|docs|assets|dist|package [target]>".into()),
    }
    Ok(())
}

// Package only an already-built binary. `dist` builds first; CI passes its target.
fn package(root: &Path, target: Option<&str>) -> Result<(), Box<dyn std::error::Error>> {
    let output = Command::new("rustc").arg("-vV").output()?;
    if !output.status.success() {
        return Err("could not determine build target".into());
    }
    let version = String::from_utf8(output.stdout)?;
    let host = version
        .lines()
        .find_map(|line| line.strip_prefix("host: "))
        .ok_or("rustc did not report its host target")?;
    let explicit_target = target;
    let target = target.unwrap_or(host);
    if target.is_empty()
        || !target.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
    {
        return Err("invalid build target".into());
    }
    let binary = if target.contains("windows") { "mammoth.exe" } else { "mammoth" };
    let build = if explicit_target.is_some() {
        root.join("target").join(target)
    } else {
        root.join("target")
    };
    let source = build.join("release").join(binary);
    // Fail before replacing an earlier package if the requested build is absent.
    let binary_hash = sha256(&source)?;
    let distribution = root.join("target/dist");
    let package = distribution.join(format!("mammoth-{target}"));
    if package.exists() {
        std::fs::remove_dir_all(&package)?;
    }
    std::fs::create_dir_all(&package)?;
    std::fs::copy(source, package.join(binary))?;
    for name in ["LICENSE-APACHE", "LICENSE-MIT"] {
        std::fs::copy(root.join(name), package.join(name))?;
    }
    std::fs::copy(root.join("deploy/RELEASE-README.md"), package.join("README.md"))?;
    for name in ["IMPLEMENTATION-STATUS.md", "OPERATIONS.md", "RELEASE-READINESS.md"] {
        let text = std::fs::read_to_string(root.join("docs").join(name))?;
        // These notes are also read from source. Make their relative links work
        // in the compact binary archive without shipping an entire source tree.
        std::fs::write(package.join(name), repository_links(&text))?;
    }
    std::fs::copy(root.join("deploy/mammoth.toml"), package.join("mammoth.toml"))?;
    let revision = git_output(root, &["rev-parse", "HEAD"])?;
    let dirty = !git_output(root, &["status", "--porcelain"])?.is_empty();
    let info = serde_json::json!({
        "version": env!("CARGO_PKG_VERSION"), "target": target,
        "source_revision": revision, "source_dirty": dirty,
        "rustc": version.trim(), "binary_sha256": binary_hash,
        "scope": "local preview; see RELEASE-READINESS.md"
    });
    std::fs::write(
        package.join("BUILD-INFO.json"),
        format!("{}\n", serde_json::to_string_pretty(&info)?),
    )?;
    let archive = distribution.join(format!("mammoth-{target}.tar.gz"));
    let status = Command::new("tar")
        // macOS otherwise adds AppleDouble resource-fork files to portable archives.
        .env("COPYFILE_DISABLE", "1")
        .arg("-czf")
        .arg(&archive)
        .arg("-C")
        .arg(&package)
        .arg(".")
        .status()?;
    if !status.success() {
        return Err("archive creation failed".into());
    }
    std::fs::write(
        archive.with_extension("gz.sha256"),
        format!("{}  {}\n", sha256(&archive)?, archive.file_name().unwrap().to_string_lossy()),
    )?;
    println!("{}", archive.display());
    Ok(())
}

fn repository_links(text: &str) -> String {
    let prefix = "https://github.com/ProjectOrcha/Mammoth/blob/AI_coded/";
    let mut output = text.to_owned();
    for path in [
        "RELEASE-READINESS.md",
        "OPERATIONS.md",
        "STORAGE-ENGINE.md",
        "MEMORY-ENGINE.md",
        "BENCHMARKS.md",
        "BENCHMARKS-LEGACY.md",
        "guide/BRANCHES.md",
    ] {
        output = output.replace(&format!("]({path})"), &format!("]({prefix}docs/{path})"));
    }
    for path in ["deploy/compose/docker-compose.yml", "deploy/systemd/mammoth.service"] {
        output = output.replace(&format!("](../{path})"), &format!("]({prefix}{path})"));
    }
    output
}

fn git_output(root: &Path, args: &[&str]) -> Result<String, Box<dyn std::error::Error>> {
    let result = Command::new("git").args(args).current_dir(root).output()?;
    if !result.status.success() {
        return Err("could not record package source revision".into());
    }
    Ok(String::from_utf8(result.stdout)?.trim().to_owned())
}

fn sha256(path: &Path) -> std::io::Result<String> {
    let mut file = std::fs::File::open(path)?;
    let mut digest = Sha256::new();
    let mut buffer = [0u8; 65536];
    loop {
        let count = file.read(&mut buffer)?;
        if count == 0 {
            break;
        }
        digest.update(&buffer[..count]);
    }
    Ok(format!("{:x}", digest.finalize()))
}

fn command(dir: &Path, program: &str, args: &[&str]) -> Result<(), Box<dyn std::error::Error>> {
    let status = Command::new(program).args(args).current_dir(dir).status()?;
    if !status.success() {
        return Err(format!("{program} {} failed ({status})", args.join(" ")).into());
    }
    Ok(())
}

fn render_help(mut command: clap::Command, name: &str, output: &mut String) {
    command = command.bin_name(name).color(clap::ColorChoice::Never);
    // Build first so child commands inherit global flags just like the CLI.
    command.build();
    output.push_str(&format!(
        "## `{name}`\n\n```text\n{}\n```\n\n",
        command
            .render_long_help()
            .to_string()
            .lines()
            .map(str::trim_end)
            .collect::<Vec<_>>()
            .join("\n")
    ));
    for child in command.get_subcommands().filter(|child| child.get_name() != "help") {
        render_help(child.clone(), &format!("{name} {}", child.get_name()), output);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reference_includes_nested_commands_and_global_flags() {
        let mut text = String::new();
        render_help(cli::Cli::help_command(), "mammoth", &mut text);
        assert!(text.contains("## `mammoth viz blocks`"));
        let blocks = text.split("## `mammoth viz blocks`").nth(1).unwrap();
        assert!(blocks.split("## ").next().unwrap().contains("--json"));
        assert!(!text.contains('\u{1b}'));
    }
}
